"""
Writer Agent

Responsibilities:
- Generate IEEE-style research paper
- Generate each section independently
- Assemble final paper
"""

from __future__ import annotations

import streamlit as st

from langchain_core.messages import HumanMessage
from langchain_groq import ChatGroq

from core.prompts import (
    ABSTRACT_PROMPT,
    INTRODUCTION_PROMPT,
    WRITER_PROMPT,
)


# ==========================================================
# Load LLM
# ==========================================================

@st.cache_resource
def load_llm():

    return ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.3,
    )


# ==========================================================
# Build Context
# ==========================================================

def build_context(state):

    context = f"""
Research Topic

{state['query']}


=========================

Literature Review

=========================

{state.get('literature_review','')}


=========================

Research Gaps

=========================

{state.get('research_gaps','')}


=========================

Novel Ideas

=========================

{state.get('novel_ideas','')}
"""

    return context

def generate_abstract(
    llm,
    context,
):

    prompt = f"""
{ABSTRACT_PROMPT}

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_introduction(
    llm,
    context,
):

    prompt = f"""
{INTRODUCTION_PROMPT}

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_literature_review(
    llm,
    context,
):

    prompt = f"""
Write the Literature Review section.

Use only the supplied context.

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_methodology(
    llm,
    context,
):

    prompt = f"""
Propose a detailed methodology.

Use the novel idea generated by the Planner.

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_expected_results(
    llm,
    context,
):

    prompt = f"""
Generate Expected Results.

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_future_work(
    llm,
    context,
):

    prompt = f"""
Generate Future Work.

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content

def generate_conclusion(
    llm,
    context,
):

    prompt = f"""
Generate the Conclusion.

Context

{context}
"""

    response = llm.invoke(
        [
            HumanMessage(
                content=prompt
            )
        ]
    )

    return response.content


